"""
Fine-tune BAAI/bge-large-en-v1.5 on UK planning policy domain data.

Training signal: (question, source_chunk) pairs from a DEDICATED training set
(data/finetune_train_pairs.json) that is strictly disjoint from the golden
evaluation dataset (data/golden_dataset.json).

IMPORTANT — methodology fix:
  An earlier version of this script trained directly on golden_dataset.json,
  the same 60 Q&A pairs used to evaluate every RAGAS experiment. That is
  train/test leakage — the model was taught the exact (question, chunk) pairs
  it was later "tested" on, which inflates every result built on the resulting
  model. This version trains on a separate, larger set generated by
  scripts/generate_finetune_dataset.py, and hard-asserts zero chunk_id overlap
  with the golden set before training starts.

Loss: MultipleNegativesRankingLoss
  - Each (question, chunk) pair is a positive
  - All other chunks in the same batch are treated as negatives
  - Forces the model to distinguish between similar-looking policy chunks

Output: outputs/bge-planning-finetuned-v2/
  (kept separate from the original outputs/bge-planning-finetuned/ so the
  leaky and leak-free models can both be evaluated for direct comparison)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from datasets import Dataset as HFDataset
from rich.console import Console
from sentence_transformers import SentenceTransformer
from sentence_transformers.sentence_transformer.losses import MultipleNegativesRankingLoss
from sentence_transformers.sentence_transformer.trainer import SentenceTransformerTrainer
from sentence_transformers.sentence_transformer.training_args import SentenceTransformerTrainingArguments

console = Console()

BASE_MODEL   = "BAAI/bge-large-en-v1.5"
TRAIN_PATH   = PROJECT_ROOT / "data" / "finetune_train_pairs.json"
GOLDEN_PATH  = PROJECT_ROOT / "data" / "golden_dataset.json"
CHUNKS_PATH  = PROJECT_ROOT / "outputs" / "chunks.jsonl"
OUTPUT_DIR   = PROJECT_ROOT / "outputs" / "bge-planning-finetuned-v2"
EPOCHS         = 3
BATCH_SIZE     = 16
LEARNING_RATE  = 2e-5


def load_json(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_chunk_lookup(path: Path) -> dict[str, str]:
    lookup: dict[str, str] = {}
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                chunk = json.loads(line)
                lookup[chunk["chunk_id"]] = chunk["text"]
    return lookup


def assert_no_leakage(train_pairs: list[dict], golden: list[dict]) -> None:
    """Hard stop if any training pair's source chunk was used in the golden evaluation set."""
    train_ids  = {p["source_chunk_id"] for p in train_pairs if p.get("source_chunk_id")}
    golden_ids = {g["source_chunk_id"] for g in golden if g.get("source_chunk_id")}
    overlap = train_ids & golden_ids
    if overlap:
        console.print(f"[red]FATAL: {len(overlap)} training chunk IDs overlap with the golden evaluation set:[/red]")
        for cid in list(overlap)[:10]:
            console.print(f"  [red]{cid}[/red]")
        console.print("[red]Refusing to fine-tune on leaked data. Regenerate the training set.[/red]")
        raise SystemExit(1)
    console.print(f"[green]Leakage check passed: {len(train_ids)} training chunk IDs, {len(golden_ids)} golden chunk IDs, 0 overlap.[/green]")


def build_training_pairs(
    train_pairs: list[dict],
    chunk_lookup: dict[str, str],
) -> tuple[list[str], list[str]]:
    questions: list[str] = []
    chunks: list[str] = []
    skipped = 0
    for item in train_pairs:
        chunk_id = item.get("source_chunk_id", "")
        chunk_text = chunk_lookup.get(chunk_id, "")
        if not chunk_text:
            skipped += 1
            continue
        questions.append(item["question"])
        chunks.append(chunk_text)
    console.print(f"Training pairs: {len(questions)} (skipped {skipped} with missing chunk)")
    return questions, chunks


def main() -> None:
    console.print(f"[bold blue]Fine-tuning {BASE_MODEL} on UK planning policy data (leak-free)[/bold blue]")

    if not TRAIN_PATH.exists():
        console.print(f"[red]Training set not found at {TRAIN_PATH}[/red]")
        console.print("[yellow]Run: python scripts/generate_finetune_dataset.py first[/yellow]")
        return
    if not GOLDEN_PATH.exists():
        console.print(f"[red]Golden dataset not found at {GOLDEN_PATH} — cannot verify no leakage. Aborting.[/red]")
        return
    if not CHUNKS_PATH.exists():
        console.print(f"[red]Chunks not found at {CHUNKS_PATH}[/red]")
        return

    train_pairs = load_json(TRAIN_PATH)
    golden      = load_json(GOLDEN_PATH)
    console.print(f"Loaded {len(train_pairs)} training pairs, {len(golden)} golden evaluation pairs")

    # ── Hard leakage check — refuses to proceed on any overlap ───────────────
    assert_no_leakage(train_pairs, golden)

    chunk_lookup = load_chunk_lookup(CHUNKS_PATH)
    console.print(f"Loaded {len(chunk_lookup)} chunk texts")

    questions, chunk_texts = build_training_pairs(train_pairs, chunk_lookup)
    if len(questions) < 10:
        console.print("[red]Too few training pairs — check finetune_train_pairs.json chunk IDs match chunks.jsonl[/red]")
        return

    train_dataset = HFDataset.from_dict({"anchor": questions, "positive": chunk_texts})
    console.print(f"Training dataset: {len(train_dataset)} pairs")

    console.print(f"[bold]Loading base model: {BASE_MODEL}[/bold]")
    model = SentenceTransformer(BASE_MODEL)
    loss   = MultipleNegativesRankingLoss(model)

    total_steps = (len(train_dataset) // BATCH_SIZE) * EPOCHS
    warmup_steps = max(1, int(total_steps * 0.1))

    args = SentenceTransformerTrainingArguments(
        output_dir=str(OUTPUT_DIR),
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        learning_rate=LEARNING_RATE,
        warmup_steps=warmup_steps,
        fp16=True,
        save_strategy="no",   # no mid-training checkpoints — saves disk space
        logging_steps=5,
        run_name="bge-planning-finetune-v2",
    )

    trainer = SentenceTransformerTrainer(
        model=model,
        args=args,
        train_dataset=train_dataset,
        loss=loss,
    )

    console.print(f"[bold]Training for {EPOCHS} epochs on {len(train_dataset)} pairs...[/bold]")
    trainer.train()

    model.save_pretrained(str(OUTPUT_DIR))
    console.print(f"[green]Fine-tuned model saved to {OUTPUT_DIR}[/green]")
    console.print("[dim]Now re-run: exp04_domain_embeddings, exp05_graph_rag, exp06_hierarchical_tuned, exp07_llm_graph_rag, exp08_hierarchical_graph_rag[/dim]")


if __name__ == "__main__":
    main()
